REVOKE ALL PRIVILEGES ON agent_threads FROM PUBLIC;
REVOKE ALL PRIVILEGES ON agent_messages FROM PUBLIC;
REVOKE ALL PRIVILEGES ON agent_turns FROM PUBLIC;
REVOKE ALL PRIVILEGES ON agent_plans FROM PUBLIC;
REVOKE ALL PRIVILEGES ON agent_approvals FROM PUBLIC;
REVOKE ALL PRIVILEGES ON agent_input_bundles FROM PUBLIC;
REVOKE ALL PRIVILEGES ON agent_input_files FROM PUBLIC;

GRANT SELECT, INSERT, UPDATE ON agent_threads TO omics_app;
REVOKE DELETE, TRUNCATE, REFERENCES, TRIGGER ON agent_threads FROM omics_app;

GRANT SELECT, INSERT ON agent_messages TO omics_app;
REVOKE UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON agent_messages FROM omics_app;

GRANT SELECT, INSERT, UPDATE ON agent_turns TO omics_app;
REVOKE DELETE, TRUNCATE, REFERENCES, TRIGGER ON agent_turns FROM omics_app;

GRANT SELECT, INSERT, UPDATE ON agent_plans TO omics_app;
REVOKE DELETE, TRUNCATE, REFERENCES, TRIGGER ON agent_plans FROM omics_app;

GRANT SELECT, INSERT, UPDATE ON agent_approvals TO omics_app;
REVOKE DELETE, TRUNCATE, REFERENCES, TRIGGER ON agent_approvals FROM omics_app;

GRANT SELECT, INSERT, UPDATE ON agent_input_bundles TO omics_app;
REVOKE DELETE, TRUNCATE, REFERENCES, TRIGGER ON agent_input_bundles FROM omics_app;

GRANT SELECT, INSERT ON agent_input_files TO omics_app;
REVOKE UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON agent_input_files FROM omics_app;

GRANT SELECT, INSERT, UPDATE ON agent_runs TO omics_app;
REVOKE DELETE, TRUNCATE, REFERENCES, TRIGGER ON agent_runs FROM omics_app;

GRANT SELECT, INSERT ON agent_events TO omics_app;
REVOKE UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON agent_events FROM omics_app;
