import { Activity, RefreshCw } from "lucide-react";
import { useState } from "react";
import type { AgentTraceEventResponse } from "../api-types";

export function TracePanel({
  events,
  loading,
  onRefresh,
}: {
  events: AgentTraceEventResponse[];
  loading: boolean;
  onRefresh: () => void;
}) {
  const [expanded, setExpanded] = useState(false);
  const latest = events[events.length - 1];

  return (
    <section className="trace-panel" aria-label="Trace and evaluation evidence">
      <div className="trace-heading">
        <button type="button" className="trace-toggle" onClick={() => setExpanded(value => !value)} aria-expanded={expanded}>
          <Activity size={15} />
          <span>
            <span className="context-label">Trace evidence</span>
            <strong>{loading ? "Refreshing" : `${events.length} event${events.length === 1 ? "" : "s"}`}</strong>
          </span>
        </button>
        <button type="button" className="trace-refresh" onClick={onRefresh} disabled={loading} aria-label="Refresh trace" title="Refresh trace">
          <RefreshCw size={14} className={loading ? "spinning" : ""} />
        </button>
      </div>
      {expanded && (
        <>
          {latest && <p className="trace-latest">Latest: {latest.name} ({latest.outcome || "pending"})</p>}
          {events.length > 0 ? (
            <ol className="trace-list">
              {events.map(event => (
                <li key={event.event_id}>
                  <div><strong>{event.name}</strong><small>{event.event_type} · {event.component}</small></div>
                  <span>{event.latency_ms == null ? "-" : `${Math.round(event.latency_ms)} ms`}</span>
                </li>
              ))}
            </ol>
          ) : (
            <p className="trace-empty">Trace events will appear after a turn is processed.</p>
          )}
          <div className="eval-evidence">
            <span className="context-label">Eval v2</span>
            <p>Deterministic release-gate reports are generated by the repository CLI.</p>
          </div>
        </>
      )}
    </section>
  );
}
