"""OmicsPrism Copilot 的受控 agent 运行时契约。"""

from .schemas import GroundedAnswer, RunState, ToolResult, VerifierVerdict
from .dataset_profile import DatasetProfile, GroupProfile, MatrixProfile, MetadataProfile, build_dataset_profiles
from .fingerprint import compute_input_fingerprint
from .param_resolver import (
    AnalysisParams,
    AnalysisProposal,
    ContrastSpec,
    DEGParams,
    DEMParams,
    GMAParams,
    MissingParam,
    ResolvedRequest,
    ScopeSpec,
    ScopeMode,
    resolve_analysis_request,
)
from .validation import (
    DatasetRef,
    Issue,
    ValidationReport,
    derive_scoped_dataset_refs,
    validate_analysis_request,
)
from .model import VllmGraphModel
from .context import (
    AnalysisModelContext,
    ContextAssembler,
    ConversationMemory,
    DecisionLedger,
    FactIndex,
    JobContextRef,
    MainModelContext,
    QaFactIndex,
    QaModelContext,
    RecentMessage,
    RecentMessages,
    ResultFocusContext,
    ResultQaModelContext,
    WorkingSet,
)
from .queue import AgentTurnInput
from .graph import PendingPlan, PlanVersionConflict, ProvenanceSource, StratumSummary
from .product_store import InMemoryAgentProductStore, PostgresAgentProductStore
from .trace import AgentTraceEvent, ModelUsage, TraceRecorder
from .tools import (
    AgentInputFile,
    AgentToolRuntime,
    ToolConfigurationError,
)
from .mcp_adapter import CapabilityMCPServer, MCPTraceContext, build_readonly_mcp_server
from .capabilities import openai_tool_definitions, readonly_openai_tool_definitions
from .readonly_tools import (
    ArtifactDescription,
    ArtifactDescriptionResult,
    ArtifactSchema,
    ContrastCandidate,
    ContrastEnumeration,
    DescribeArtifactsRequest,
    DescribeMetadataRequest,
    EnumerateContrastsRequest,
    ListJobsRequest,
    QueryArtifactRequest,
    JobListItem,
    JobListResult,
    MetadataDescription,
    MetadataFieldDescription,
)

__all__ = [
    "GroundedAnswer",
    "RunState",
    "ToolResult",
    "VerifierVerdict",
    "DatasetProfile",
    "MatrixProfile",
    "MetadataProfile",
    "GroupProfile",
    "build_dataset_profiles",
    "AnalysisParams",
    "AnalysisProposal",
    "ContrastSpec",
    "DEGParams",
    "DEMParams",
    "GMAParams",
    "MissingParam",
    "ResolvedRequest",
    "ScopeSpec",
    "ScopeMode",
    "resolve_analysis_request",
    "DatasetRef",
    "Issue",
    "ValidationReport",
    "derive_scoped_dataset_refs",
    "validate_analysis_request",
    "compute_input_fingerprint",
    "VllmGraphModel",
    "AnalysisModelContext",
    "ContextAssembler",
    "ConversationMemory",
    "FactIndex",
    "DecisionLedger",
    "JobContextRef",
    "WorkingSet",
    "MainModelContext",
    "QaFactIndex",
    "QaModelContext",
    "RecentMessage",
    "RecentMessages",
    "ResultFocusContext",
    "ResultQaModelContext",
    "AgentTurnInput",
    "PendingPlan",
    "PlanVersionConflict",
    "ProvenanceSource",
    "StratumSummary",
    "InMemoryAgentProductStore",
    "PostgresAgentProductStore",
    "AgentTraceEvent",
    "ModelUsage",
    "TraceRecorder",
    "AgentInputFile",
    "AgentToolRuntime",
    "ToolConfigurationError",
    "CapabilityMCPServer",
    "MCPTraceContext",
    "build_readonly_mcp_server",
    "openai_tool_definitions",
    "readonly_openai_tool_definitions",
    "ArtifactDescription",
    "ArtifactDescriptionResult",
    "ArtifactSchema",
    "ContrastCandidate",
    "ContrastEnumeration",
    "DescribeArtifactsRequest",
    "DescribeMetadataRequest",
    "EnumerateContrastsRequest",
    "ListJobsRequest",
    "QueryArtifactRequest",
    "JobListItem",
    "JobListResult",
    "MetadataDescription",
    "MetadataFieldDescription",
]
